Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maids-task
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true